<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-05 19:12
=======
# Generated by Django 4.2.3 on 2023-07-21 01:56
>>>>>>> 412f5edb1f16317d38d008c4e15d2479e221f630

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import location_field.models.plain
=======
>>>>>>> 412f5edb1f16317d38d008c4e15d2479e221f630


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Arts', 'Arts'), ('Music', 'Music'), ('Health', 'Health'), ('Games', 'Games'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Support', 'Support')], default='Arts', max_length=128)),
                ('modality', models.CharField(choices=[('Online', 'Online'), ('In-person', 'In-person')], default='Virtual', max_length=128)),
                ('city', models.CharField(choices=[('Los Angeles', 'Los Angeles'), ('San Francisco', 'San Francisco'), ('San Diego', 'San Diego'), ('Sacramento', 'Sacramento'), ('San Jose', 'San Jose'), ('Oakland', 'Oakland'), ('Long Beach', 'Long Beach'), ('Fresno', 'Fresno'), ('Bakersfield', 'Bakersfield'), ('Santa Ana', 'Santa Ana')], default='San Diego', max_length=128)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_picker', models.DateField(blank=True, null=True)),
                ('time_picker', models.TimeField()),
                ('end_picker', models.TimeField(default=None, null=True)),
                ('thumbnail', models.ImageField(default=None, null=True, upload_to='event_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.status')),
>>>>>>> 412f5edb1f16317d38d008c4e15d2479e221f630
            ],
        ),
    ]
