# Generated by Django 4.2.3 on 2023-07-11 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_picker', models.DateField(default=datetime.datetime(2023, 7, 10, 17, 53, 45, 941741))),
                ('time_picker', models.TimeField()),
                ('end_picker', models.TimeField(default=None, null=True)),
                ('thumbnail', models.ImageField(default=None, null=True, upload_to='event_images')),
            ],
        ),
    ]
