# Generated by Django 4.2.2 on 2023-08-04 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_end_time_alter_event_start_time_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default='draft', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.status'),
        ),
    ]
