# Generated by Django 4.2.2 on 2023-07-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_location_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
