# Generated by Django 4.2.2 on 2023-07-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='favorite',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
