# Generated by Django 4.2.2 on 2023-07-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_ticket_status_favorite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Draft', max_length=128),
        ),
    ]
